
 export const PLAYER_REQUEST = 'PLAYER_REQUEST'
 export const PLAYER_FAILURE = 'PLAYER_FAILURE'
 export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCPLAYER'



 export const AUTH_REQUEST = 'AUTH_REQUEST'
 export const AUTH_FAILURE = 'AUTH_FAILURE'
 export const POST_AUTH_SUCCESS = 'POST_AUTH_SUCCESS'
 


